/** Seed data only — swapping in real Supabase queries means replacing just this file. */
import type { FoodEntry } from './models';

export const foodLog: FoodEntry[] = [
  {
    id: 'f1',
    name: 'Greek yogurt with berries',
    meal: 'breakfast',
    servings: 1,
    servingLabel: '1 bowl',
    calories: 210,
    protein: 18,
    carbs: 24,
    fat: 4,
    tier: 1,
  },
  {
    id: 'f2',
    name: 'Turkey sandwich',
    meal: 'lunch',
    servings: 1,
    servingLabel: '1 sandwich',
    calories: 460,
    protein: 32,
    carbs: 48,
    fat: 14,
    tier: 3,
  },
  {
    id: 'f3',
    name: 'Graham crackers',
    meal: 'dinner',
    servings: 1,
    servingLabel: '2 sheets',
    calories: 130,
    protein: 2,
    carbs: 24,
    fat: 3,
    tier: 4,
  },
  {
    id: 'f4',
    name: 'Oat milk, original',
    brand: 'Oatly',
    meal: 'dinner',
    servings: 1.5,
    servingLabel: '240 ml',
    calories: 180,
    protein: 3,
    carbs: 27,
    fat: 7,
    tier: 3,
  },
  {
    id: 'f5',
    name: 'Chili, homemade',
    meal: 'dinner',
    servings: 1,
    servingLabel: '1 bowl',
    calories: 310,
    protein: 28,
    carbs: 24,
    fat: 9,
    tier: 2,
    tierOverridden: true,
  },
];
